stages:
  - build
  - test

variables:
  IMAGE_NAME: "sync-icloud-to-git"
  TAG: 0.1.2

.default-before-script: &default-before-script 
  - 'echo "Runner info: $CI_RUNNER_DESCRIPTION"'
  - cat /etc/os-release
  - env | sort

build-docker-image:
  stage: build
  image: registry.pwlab.dev/build-tools:0.1.0
  tags:
    - kubernetes
  before_script:
    - *default-before-script
  script:
    - $CI_PROJECT_DIR/run/docker_build.sh
    - $CI_PROJECT_DIR/run/docker_push.sh

run-tests:
  stage: test
  image: python:3.10-slim
  tags:
    - kubernetes
  before_script:
    - *default-before-script
    - apt-get update && apt-get install -y git curl unzip
    - curl -fsSL https://rclone.org/install.sh | bash
    - pip install -e .[dev]
  script:
    - pytest tests/ --verbose --cov=sync_icloud_git --cov-report=term-missing
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week

secret-detection:
  stage: test
  image: zricethezav/gitleaks:latest 
  tags: 
    - kubernetes
  script :
    - *default-before-script
    - gitleaks detect --verbose --source=$CI_PROJECT_DIR 
